---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	r_boot(r_boot)
	r_frame0(r_frame0)
	r_hold(r_hold)
	r_scan(r_scan)
	r_fill(r_fill)
	drone_delay(drone_delay)
	drone_pull(drone_pull)
	drone_tiles(drone_tiles)
	r_fly(r_fly)
	r_assemble(r_assemble)
	r_resolve(r_resolve)
	road_build(road_build)
	drone_swoop(drone_swoop)
	r_camera(r_camera)
	r_env(r_env)
	road_preshow(road_preshow)
	r_lights(r_lights)
	road_traffic(road_traffic)
	r_boom(r_boom)
	r_dest(r_dest)
	__end__([<p>__end__</p>]):::last
	__start__ --> r_boot;
	drone_delay --> drone_pull;
	drone_pull --> drone_tiles;
	drone_swoop --> r_camera;
	drone_tiles --> r_fly;
	r_assemble --> r_resolve;
	r_boom --> r_dest;
	r_boot --> r_frame0;
	r_camera --> r_env;
	r_env --> road_preshow;
	r_fill --> drone_delay;
	r_fly --> r_assemble;
	r_frame0 --> r_hold;
	r_hold --> r_scan;
	r_lights --> road_traffic;
	r_resolve --> road_build;
	r_scan --> r_fill;
	road_build --> drone_swoop;
	road_preshow --> r_lights;
	road_traffic --> r_boom;
	r_dest --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
