"""Plain-English meaning of the version-section keys (from EDITING.md, the _about notes and the code that reads them)."""
NOTES = {
 "road.build_start_s": "When the road starts building (s after the QR fills the screen).", "road.build_s": "How long the road takes to build out.", "road.build_radius": "How far the world builds out (metres).",
 "road.cars": "Cars in the queue (0-5).", "road.car_speed": "Car cruising speed (m/s).", "road.car_accel": "Car acceleration (m/s2).", "road.workers": "Traffic controllers (0-3).",
 "road.fog_near": "Haze starts this far behind the unit.", "road.fog_far": "Haze is full this far behind the unit.", "road.green_s": "Green time in road (replaces lights.green_s).",
 "road.amber_s": "Amber time in road.", "road.red_hold_s": "Red before the boom drops, in road.", "road.leave_after_s": "Pause after the boom is down before DEST, in road.", "road.boom_down_wait_s": "How long the boom stays down before it rises for green.",
 "minions.count": "How many minis (30-80).", "minions.spacing_cells": "Gap between minis in QR modules.", "minions.size": "Mini height as a share of the hero.", "minions.pop_start_s": "When the first minis pop up.",
 "minions.pop_spread_s": "How long the pop-up wave takes to reach the furthest mini.", "minions.pop_s": "How long one pop takes.", "minions.stand_up_s": "When they get up off their backs.", "minions.stand_up_spread_s": "Spread of stand-up times.",
 "minions.bob": "Bob height.", "minions.bob_hz": "Bob speed.", "minions.cycle_s": "Length of each mini's own light and boom cycle.", "minions.arm_length": "Mini boom length (share of the hero's).",
 "minions.duck_s": "When the minis between the camera and the hero duck away.", "minions.line_up_s": "When they fall into rows behind the hero.", "minions.line_up_duration_s": "How long lining up takes.",
 "minions.rows": "Rows behind the hero.", "minions.row_gap": "Gap between rows (hero heights).", "minions.col_gap": "Gap between minis in a row (hero heights).",
 "minions2.count": "How many minis try to fit (220).", "minions2.size": "Mini height as a share of the hero.", "minions2.pop_spread_s": "How long the pop-up wave takes.", "minions2.ring": "Clear ring round the hero's feet (hero heights).",
 "minions2.hero_clear": "Screen margin kept clear round the whole hero.", "minions2.depth_grow": "How much more spread out the far minis are.", "minions2.max_depth": "Furthest a mini can stand (hero heights).",
 "minions2.reach_cells": "How far past the code the spots are tried (modules).", "minions2.ripple_s": "Delay for the hero's lights and boom to reach the furthest mini.", "minions2.bob": "Bob height (minions2).",
 "domino.delay_s": "How much later than morph3 the hero's flight, resolve and glide run (0-6 s).", "domino.glide_yaw_deg": "Orbit at the end (0 = straight dolly).", "domino.topple_start_s": "When the toppling starts.",
 "domino.topple_spread_s": "How long the wave takes from the corners to the middle.", "domino.topple_s": "How long one module takes to fall.", "domino.overshoot": "Bounce as a module lands.",
 "domino.size": "Mini height (hero heights).", "domino.aisle_width": "Aisle width (hero heights).", "domino.lines_per_side": "Lines of minis each side (1-4).", "domino.line_gap": "Gap between the lines.",
 "domino.row_gap": "Gap between rows along the aisle.", "domino.first_row": "Where the first row starts.", "domino.max_rows": "Most rows.", "domino.flip_s": "How long a fallen module takes to flip up.",
 "domino.stand_delay_s": "Delay between falling and flipping up.", "domino.swoop_start_s": "When the camera starts down into the aisle.", "domino.swoop_s": "How long the swoop down takes.",
 "domino.dolly_s": "How long the trip along the aisle takes.", "domino.dolly_start": "Where along the aisle the dolly starts.", "domino.camera_height": "Camera height in the aisle (hero heights).",
 "domino.look_height": "Height the camera looks at.", "domino.salute_lead": "How far ahead of the camera rows raise their booms.", "domino.salute_s": "How fast a row raises its booms.",
 "domino.ripple_s": "How long the hero's lights and boom drop take to ripple down the rows.", "domino.hero_clear": "Space kept clear round the hero in the end shot.",
 "domino2.count": "About how many minis.", "domino2.size": "Mini height (hero heights).", "domino2.size_mix": "How much the sizes vary.", "domino2.yaw_jitter": "How much each mini is turned its own way.",
 "domino2.grid": "How finely spots are tried.", "domino2.reach_x": "How far out to the sides (hero heights).", "domino2.reach_back": "How far back towards the horizon.", "domino2.max_depth": "Furthest a mini can stand.",
 "domino2.depth_grow": "How much more spread out the far ones are.", "domino2.ring": "Clear ring round the hero.", "domino2.path_clear": "Width of the lane kept clear for the camera.",
 "domino2.front_min_scale": "Smallest a mini in front of the hero may shrink before it is left out.", "domino2.hero_clear": "Screen margin kept clear round the hero.", "domino2.ripple_spread": "How far the boom ripple spreads sideways.",
 "domino2.salute_jitter_s": "Random delay so booms do not rise in lockstep.", "domino2.salute_lead": "How far ahead of the camera booms rise.",
 "night.fade_s": "How long the fade to night takes.", "night.city_glow": "Glow strength of the QR city lights.", "night.light_min": "Dimmest QR light.", "night.bright_share": "Share of extra-bright lights.",
 "night.dark_share": "Share of modules that stay dark.", "night.cube_glow": "Glow on the flying cubes.", "night.cube_brighten": "Extra brightness on the cubes.", "night.road_start_s": "When the wet road spreads.",
 "night.road_s": "How long it takes to spread.", "night.road_radius": "Road size in front of the unit.", "night.road_behind": "Road size behind the unit.", "night.road_roughness": "Road gloss (lower = wetter, shinier).",
 "night.wash": "Strength of the light cycle's colour wash on the scene.", "night.wash_range": "Reach of that wash.", "night.sky_wash": "Colour wash on the sky.", "night.haze_near": "Night haze start.",
 "night.haze_far": "Night haze end.", "night.flasher_light": "Brightness of the cabinet flasher lights.", "night.flasher_range": "Reach of the flasher lights.", "night.streaks": "Strength of the reflections on the road.",
 "night.streak_length": "Length of the reflections.", "night.scene_light": "How much of the day lighting stays.",
 "drone.delay_s": "How much later than morph3 the hero's flight and resolve run.", "drone.pull_start_s": "When the camera starts rising.", "drone.pull_s": "How long the rise takes.", "drone.height": "Hover height (relative to the code).",
 "drone.centre_x": "Hover point sideways.", "drone.centre_z": "Hover point forward/back.", "drone.fov": "Drone lens angle.", "drone.transform_start_s": "When the QR starts turning into the worksite.",
 "drone.transform_s": "How long the tile-by-tile reveal takes.", "drone.tile_flip_s": "How long one tile flip takes.", "drone.random": "How random the reveal order is (0-1).", "drone.swoop_start_s": "When the swoop down starts.",
 "drone.swoop_s": "How long the swoop takes.", "drone.swoop_side": "How far the swoop swings to the side (sign picks the side).", "drone.swoop_back": "How far back it swings.", "drone.bank_deg": "Bank angle in the turn.",
 "blueprint.invert_start_s": "When the QR starts inverting to blueprint (s after the fill starts).", "blueprint.invert_s": "How long the inversion takes.", "blueprint.paper_alpha": "Sheet opacity.",
 "blueprint.label_size": "Size of the dimension text.", "blueprint.draw_start_s": "When the elevation starts drawing.", "blueprint.draw_s": "How long the drawing takes.", "blueprint.lift_start_s": "When the wireframe lifts off.",
 "blueprint.lift_s": "How long the lift and stand-up take.", "blueprint.lift_height_cells": "How high it lifts (modules).", "blueprint.wire_glow": "Wireframe glow.", "blueprint.fill_part_s": "How long each part takes to scan in.",
 "blueprint.scan_glow": "Glow of the scan ring.", "blueprint.flash": "Flash as each part completes.", "blueprint.wire_fade_start_s": "When the wireframe starts fading.", "blueprint.wire_fade_s": "How long it fades.",
 "blueprint.wire_fill_fade": "How much the wireframe fades as parts fill.", "blueprint.ink_fade_start_s": "When the sheet drawings fade.", "blueprint.ink_fade_s": "How long they fade.",
 "rain.shoot_start_s": "When the modules shoot up.", "rain.shoot_spread_s": "Spread of shoot-up times.", "rain.shoot_speed": "Shoot-up speed.", "rain.rain_start_s": "When cubes start falling.",
 "rain.rain_s": "How long the downpour lasts.", "rain.drop_height": "Fall height.", "rain.gravity": "Gravity (faster, heavier fall).", "rain.drift": "Sideways drift while falling.", "rain.tumble": "Tumble while falling.",
 "rain.layer_mix": "How much the bottom-up order is mixed.", "rain.bounce_cells": "Bounce height on landing (modules).", "rain.bounce_hz": "Bounce speed.", "rain.bounce_damping": "How fast the bounce dies away.",
 "rain.settle_s": "Time to snap into the slot.", "rain.dust": "Dust puff strength.", "rain.dust_count": "Dust particles.", "rain.dust_size": "Dust particle size.", "rain.dust_s": "How long the dust lasts.",
 "rain.dust_at_tip": "Puff at the boom tip instead of round the wheels.", "rain.shake": "Camera shake strength (0 = none).", "rain.shake_s": "Shake length.",
}
for p in ["cabinet", "head", "lenses", "boom", "wheels"]:
    NOTES[f"blueprint.fill_{p}_s"] = f"When the {p} starts to scan in."
